### ISSUE TITLE
Crash issue android 4.4

### ISSUE THREAD

**Issue by nvtuan96** [AI-HELP/unity-example#3]
Hello Guys, I am facing crash issue on Android 4.4 related to OkHttpClient
Unity: 2020.3.32
AI Help SDK: 2.5.0
Can you guy please take a look at this issue? It is urgent because crash rate is going up, Please help !!!!
![image](https://user-images.githubusercontent.com/47739604/190037103-5c7b5c26-9847-406e-a5e9-337cef02d4e6.png)

`Caused by java.lang.ExceptionInInitializerError
       at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
       at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015)
       at net.aihelp.core.ui.image.OkHttp3Downloader.<init>(OkHttp3Downloader.java:71)
       at net.aihelp.core.ui.image.OkHttp3Downloader.<init>(OkHttp3Downloader.java:50)
       at net.aihelp.core.ui.image.OkHttp3Downloader.<init>(OkHttp3Downloader.java:40)
       at net.aihelp.core.ui.image.Picasso$Builder.build(Picasso.java:889)
       at net.aihelp.init.AIHelpCore.init(AIHelpCore.java:49)
       at net.aihelp.init.AIHelpSupport$1.run(AIHelpSupport.java:65)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5045)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
       at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by Joeljt** [comment]
We believe this issue is happening because you're using a version of okhttp greater than 3.12.13, as 3.x is the last version supporting Android Kitkat. You can fix this by downgrade your okhttp version.

Sorry for the late reply, though. You can reach out to us by sending email to support@aihelp.net.
